name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build Docker image
        run: ./tasks build

      - name: Push Docker image
        run: gitsha=$(git rev-parse --short HEAD);docker push siavashoutadi/backstage-deploy:$gitsha
